### PR TITLE
Allow new background state runners

### PR DESCRIPTION
**Pull request by DanielRBaird**
We have run into issues on android where an Iso mutable collection has it's thread interrupted while it is in the middle of processing something. While looking into this code, we realized that all of the edits were happening on a single thread.

The default behavior is likely okay for a lot of things, but some mission critical things we want to be able to split off onto their own threads using a unique runner. We figure this will help to reduce bottlenecks that could be caused by a ton of collection manipulation all using a single thread, and we will be less likely to have our threads interrupted. 

The changes here are intended to:
- Allow users to create new instances of BackgroundStateRunner
- Optionally create new collections using different background state runners.

Note: Currently changing the constructor will be a minor breaking change, but we could eliminate that inconvenience by adding a new constructor instead of adding on to the existing one.

### CODE REVIEW

**Comment by DanielRBaird** [comment]
@kpgalligan, apparently I need to make another change to make ktlint happy, but I'm interested in your feedback here... ff you are interested in merging this change or if you have any suggestions for alternatives.

**Comment by kpgalligan** [comment]
Looking...

**Comment by kpgalligan** [comment]
I made a change to move constructor order so the last is the producer lambda, so you could have

```kotlin
IsolateState { mutableListOf<SomeData>() }
```

instead of

```kotlin
IsolateState({ mutableListOf<SomeData>() })
```

Was there a reason behind the constructor param order?

https://github.com/touchlab/Stately/commit/a5edc2b257c2a69577a44fa1d729a8dbd4c94aad

**Comment by DanielRBaird** [comment]
> I made a change to move constructor order so the last is the producer lambda, so you could have
> 
> ```kotlin
> IsolateState { mutableListOf<SomeData>() }
> ```
> 
> instead of
> 
> ```kotlin
> IsolateState({ mutableListOf<SomeData>() })
> ```
> 
> Was there a reason behind the constructor param order?
> 
> [a5edc2b](https://github.com/touchlab/Stately/commit/a5edc2b257c2a69577a44fa1d729a8dbd4c94aad)

No, that makes sense.

> I made a change to move constructor order so the last is the producer lambda, so you could have
> 
> ```kotlin
> IsolateState { mutableListOf<SomeData>() }
> ```
> 
> instead of
> 
> ```kotlin
> IsolateState({ mutableListOf<SomeData>() })
> ```
> 
> Was there a reason behind the constructor param order?
> 
> [a5edc2b](https://github.com/touchlab/Stately/commit/a5edc2b257c2a69577a44fa1d729a8dbd4c94aad)

No, that order does make more sense. 👍

**Pull request merged**
