### PR TITLE
Make stateExecutor of BackgroundStateRunner use daemon thread

### LINKED ISSUE #34: dispose() is not closing internal ThreadExecutor
When using collections on JVM,  StateHolder leverages defaultStateRunner (BackgroundStateRunner for JVM) which in turn creates Executors.newSingleThreadExecutor().
As a result java application cannot finish ( non-daemon thread is running ).
To resolve this dispose would need to close that Executor, and let application that uses this library to exit.

### PR DESCRIPTION
**Pull request by CommanderTvis**
closes #34

### CODE REVIEW

**Comment by benasher44** [comment]
I think with #57, you can now provide this implementation yourself

**Comment by ArcticLampyrid** [comment]
A more user-friendly default state runner is still useful.

**Comment by ArcticLampyrid** [comment]
JS `BackgroundStateRunner` does not need close as it's actually a single-thread platform.
Native `BackgroundStateRunner` can safely leak a worker (`kotlinx.coroutines` designed to leak a default worker to the end. It is **harmless**).
JVM `BackgroundStateRunner` must be closed manually as we use non-daemon thread, but if the daemon flag is set, it can be leak **safely**. (so did `kotlinx.coroutines`)

Then we can remove function designed to close ***default*** background state runner. BTW, we prevent the exception that users try to create a state when default background state runner is closed, as default runner is usually considered available all the time. 
(`kotlinx.coroutines` forbid disposing default scheduler)

**Comment by ArcticLampyrid** [comment]
@benasher44 
Still think it's worth merging.

**Pull request closed without merging**
